dist: xenial # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  
os:
  - linux
  
virtualenv:
  system_site_packages: true
  
install:
  - pip install --upgrade pip
  - pip install ShareMount
